### ISSUE TITLE
Error: STARK_API_KEY environment variable is not set, how do we get STARK_API_KEY?

### ISSUE THREAD

**Issue by sanoj-s** [AppiumTestDistribution/stark-vision#3]
I have successfully installed stark-vision and started the Stark Server and getting the below exception:

info StarkVision Updating server with StarkVision plugin
info StarkVision 📱 CLI Args: {"waitTimeOut":20000,"interval":500,"debug":false,"visibleExplanation":false}
ERR! StarkVision Error: STARK_API_KEY environment variable is not set
ERR! StarkVision     at C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:8379480
ERR! StarkVision     at Generator.next (<anonymous>)
ERR! StarkVision     at C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:8328136
ERR! StarkVision     at new Promise (<anonymous>)
ERR! StarkVision     at _0x1b2b3e (C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:8321393)
ERR! StarkVision     at Object.PSOZN (C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:3953338)
ERR! StarkVision     at _0x4f9995 (C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:8375255)
ERR! StarkVision     at Object.hvkpi (C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:3298094)
ERR! StarkVision     at Object.KeFJx (C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:8311501)
ERR! StarkVision     at C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:8392868
ERR! StarkVision     at Generator.next (<anonymous>)
ERR! StarkVision     at C:\Users\user\AppData\Roaming\npm\node_modules\stark-vision\lib\bundle.js:3:8328136
ERR! StarkVision     at new Promise (<anonymous>)

How do we get the STARK_API_KEY value?

**Comment by pruthive580** [comment]
same here

@saikrishna321 can you help ?

CLI Args: {"waitTimeOut":20000,"interval":500,"debug":false,"visibleExplanation":false}
ERR! StarkVision Error: STARK_API_KEY environment variable is not set
ERR! StarkVision     at /Users/bhargav/node_modules/stark-vision/lib/bundle.js:3:8379480

**Comment by saikrishna321** [comment]
@sanoj-s @pruthive580 We are closed for beta program now. If your org is interested please write to atddevs@gmail.com 

We can provision a trial license and take it further.

**Comment by anhtester** [comment]
How to get STARK_API_KEY ??

<img width="1721" height="880" alt="Image" src="https://github.com/user-attachments/assets/8f1170ec-61dd-4ff2-91bd-6d57e8e53d58" />

**Comment by saikrishna321** [comment]
@anhtester https://github.com/AppiumTestDistribution/stark-vision/issues/3#issuecomment-2540809258

**Comment by Noah-Access** [comment]
Can we have a video demo on the github so i can know its working?
